{
 "title": "Спидометр",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "COUNT",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM alarm_logs LIMIT 50 "
    }
   ]
  },
  {
   "title": "DataBase",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select * from alarm_logs\r\norder by timestamp"
    }
   ]
  },
  {
   "title": "State count ",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT state, COUNT(*) AS count  \r\nFROM alarm_logs  \r\nGROUP BY state  \r\nORDER BY count"
    }
   ]
  }
 ]
}